name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Run nix flake check
      run: nix flake check
    - name: Test module evaluation with servers
      run: nix-instantiate --eval tests/test-recursion.nix
    - name: Test actual NixOS build (dry-run)
      run: nix-build '<nixpkgs/nixos>' --attr config.system.build.toplevel -I nixos-config=configuration.nix --dry-run