name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Run nix flake check
      run: nix flake check
    - name: Test Build
      run: nix-shell -p nixos-rebuild --command 'nixos-rebuild build --flake .#test'
